% 1k train
save_path = './selective_search_cache/1k_train'; ...
mkdir(save_path); ...
load imdb/cache/imdb_ilsvrc12_loc_train.mat; ...
selective_search_boxes_imdb(imdb, save_path);

% 1k val
save_path = './selective_search_cache/1k_val'; ...
mkdir(save_path); ...
load imdb/cache/imdb_ilsvrc12_loc_val.mat; ...
selective_search_boxes_imdb(imdb, save_path);

% 3k train
save_path = './selective_search_cache/3k_train'; ...
mkdir(save_path); ...
load imdb/cache/imdb_imagenet3k_loc_train.mat; ...
selective_search_boxes_imdb(imdb, save_path);

% 3k val
save_path = './selective_search_cache/3k_val'; ...
mkdir(save_path); ...
load imdb/cache/imdb_imagenet3k_loc_val.mat; ...
selective_search_boxes_imdb(imdb, save_path);